# Generated by Django 5.1.3 on 2024-11-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cd',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dvd',
            options={},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
    ]
