# Generated by Django 5.1.3 on 2024-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0002_media_creator_name_media_creator_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='cd',
            options={'verbose_name_plural': 'CDs'},
        ),
        migrations.AlterModelOptions(
            name='dvd',
            options={'verbose_name_plural': 'DVDs'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.RemoveField(
            model_name='media',
            name='creator_name',
        ),
        migrations.RemoveField(
            model_name='media',
            name='creator_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cd',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='director',
            field=models.CharField(max_length=100),
        ),
    ]
