# Generated by Django 5.1.3 on 2024-11-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0005_borrow_is_returned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'verbose_name_plural': 'BoardGames'},
        ),
    ]
