# Generated by Django 5.1.3 on 2024-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0006_alter_boardgame_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
