# Generated by Django 5.1.3 on 2024-11-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0007_alter_borrow_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
